# Generated by Django 5.2.12 on 2026-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('second_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('looking_for', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('star', models.CharField(blank=True, max_length=100, null=True)),
                ('rasi', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_caste', models.CharField(blank=True, max_length=100, null=True)),
                ('gothram', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('schooling', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation', models.CharField(blank=True, max_length=255, null=True)),
                ('masters', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_exp', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_status', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_native', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_native', models.CharField(blank=True, max_length=255, null=True)),
                ('siblings', models.TextField(blank=True, null=True)),
                ('parents_staying', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_property', models.TextField(blank=True, null=True)),
                ('shared_property', models.TextField(blank=True, null=True)),
                ('expected_property', models.TextField(blank=True, null=True)),
                ('preferred_height', models.CharField(blank=True, max_length=50, null=True)),
                ('age_gap', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_sub_caste', models.CharField(blank=True, max_length=100, null=True)),
                ('astrology', models.CharField(blank=True, max_length=100, null=True)),
                ('looking_country', models.CharField(blank=True, max_length=100, null=True)),
                ('looking_state', models.CharField(blank=True, max_length=100, null=True)),
                ('education_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('career_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('story_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
