# Generated by Django 5.2.12 on 2026-03-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_generatedpdf_generationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
