# Generated by Django 5.2.12 on 2026-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpdf',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='premium', max_length=20),
        ),
    ]
