# Generated by Django 5.2.12 on 2026-03-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_add_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pdf_generated', 'PDF Generated'), ('pdf_previewed', 'PDF Previewed'), ('pdf_downloaded', 'PDF Downloaded'), ('pdf_emailed', 'PDF Emailed'), ('photo_uploaded', 'Photo Uploaded'), ('photo_deleted', 'Photo Deleted'), ('profile_synced', 'Profile Synced'), ('bulk_pdf_generated', 'Bulk PDF Generated')], max_length=50)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
