# Generated by Django 5.2.12 on 2026-03-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('matched', 'Matched'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
    ]
