# Generated by Django 5.2.12 on 2026-03-15 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_add_profile_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('whatsapp', 'WhatsApp Chat'), ('walkin', 'Walk-in'), ('email', 'Email'), ('other', 'Other')], default='phone_call', max_length=20)),
                ('outcome', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Call Back Later'), ('docs_pending', 'Documents Pending'), ('shortlisted', 'Shortlisted Match'), ('info_gathered', 'Info Gathered'), ('no_answer', 'No Answer'), ('other', 'Other')], default='info_gathered', max_length=20)),
                ('summary', models.TextField(help_text='Key points from the conversation')),
                ('transcript', models.TextField(blank=True, default='', help_text='Full transcript (auto-generated from audio)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='call_recordings/')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
